s=str(input())
if(len(s)%2==0):
    mid1=int(len(s)/2)
    mid2=mid1-1
    s=s.replace(s[mid1],"*")
    s=s.replace(s[mid2],"*")
    print(s)
else:
    mid=int(len(s)/2)
    s=s.replace(s[mid],"*",1)
    print(s)
